from io import BytesIO

import pytest
from pypdf import PdfReader

from app.builders import pdf
from app.builders.schema import Document
from app.files.pdf_text import extract_page_text
from app.services.base import ServiceError
from app.services.pdf_to_word.test_service import configured_service


async def test_mixed_arabic_numbers_survive_pdf_extraction(tmp_path):
    lines = [
        "رقم الطلب: 00123",
        "المبلغ: 125.50 ريال",
        "المبلغ المسجل: 0 ريال",
        "رقم الطلب: 00123",
        "التاريخ: 2026-10-08",
        "المبلغ: غير مذكور",
        "English text — Acceptance 123",
    ]
    data = pdf.build(Document(title="اختبار المستند", sections=[{"paragraphs": lines}]))
    # A real PDF generated by the application's shaped-Arabic builder, not a
    # mocked extractor or an uploaded customer fixture.
    assert len(PdfReader(BytesIO(data)).pages) == 1
    service, artifact, _, ai = configured_service(tmp_path, data)
    await service.run({"pdf": artifact.key})
    extracted = ai.extract.await_args.args[1]
    assert extracted.count("00123") == 2
    for value in ["125.50", "0 :المبلغ المسجل", "2026-10-08", "غير مذكور", "رقم الطلب", lines[-1]]:
        assert value in extracted


def test_fragment_collection_enforces_limit_and_keeps_non_arabic_values():
    class Page:
        def extract_text(self, *, visitor_text):
            visitor_text("00123 ١٢٥٫٥٠ −2 0 2026-10-08 ①", None, None, None, None)
            visitor_text("\n", None, None, None, None)

    assert extract_page_text(Page(), limit=100) == "00123 ١٢٥٫٥٠ −2 0 2026-10-08 ①"
    with pytest.raises(ServiceError, match="pdf_text_too_long"):
        extract_page_text(Page(), limit=10)
